version: 2.1
orbs:
  newman: postman/newman@1.0.0
# code attribution
# Adapted from APDS 2023
# Author: Serena
# https://github.com/VCSOIT/APDS2023.git

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Run Sonar Scanner"
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            echo "Sonar org value is: $SONAR_ORG"
            sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="." \
            -Dsonar.java.binaries=build

  postman-tests-general:
    docker:
      - image: postman/newman:latest
    steps:
      - checkout
      - newman/newman-run:
          collection: server/tests/APDS.PART3.postman_collection.json
          insecure: true

  postman-tests-brute:
    docker:
      - image: postman/newman:latest
    steps:
      - checkout
      - run:
          name: "Test Brute Force Protection with Multiple Login Attempts"
          command: |
            newman run server/tests/APDS.PART3.2.postman_collection.json \
              --iteration-count 10 \
              --env-var "testType=bruteForce"

  postman-tests-ratelimit:
    docker:
      - image: postman/newman:latest
    steps:
      - checkout
      # Test Rate Limiting
      - run:
          name: "Test Rate Limiting with Multiple Requests"
          command: |
            newman run server/tests/APDS.PART3.3.postman_collection.json \
              --iteration-count 100 \
              --env-var "testType=rateLimit" \
              --delay-request 100

workflows:
  say-hello-workflow:
    jobs:
     # - sonarqube
     # - postman-tests-general
      - postman-tests-brute
    #  - postman-tests-ratelimit
